name: Deploy

on:
  workflow_run:
    workflows: ["Test services"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Archive code for deploy
        run: |
          zip -r deploy.zip . -x '*.git*' '*.github/*'

      - name: Create secrets.env file
        run: |
          echo "ADMIN_KEY=${{ secrets.ADMIN_KEY }}" >> secrets.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> secrets.env

      - name: Transfer files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: "deploy.zip,secrets.env"
          target: "/home/${{ secrets.SERVER_USER }}/deploy/"
      
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/deploy/
            unzip -o deploy.zip
            sudo docker compose build
            sudo docker compose down
            sudo docker compose up -d
            sudo docker image prune -f
            rm deploy.zip
            rm secrets.env